config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get 'dashboard', to: 'dashboard#index'

  resources :users, only: [:show, :index, :edit]

  resources :rooms

  resources :bookings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  extend OrderAsSpecified
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
      return "#{first_name} #{last_name}".strip if (first_name || last_name)
      "Anonymous"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    dashboard_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  layout :resolve_layout

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])

    # datetime_now = Time.now
    datetime_now = Time.new(2020, 01, 02, 7, 35, 0)
    @date_now = datetime_now.strftime("%A, %B %-d")
    @time_now = datetime_now.strftime("%-H:%M")

    @bookings = @room.bookings.order('start').where(start: datetime_now.all_day)
    booking_ids_ordered = @room.bookings.order('start').where(start: datetime_now.all_day).ids

  end

  private
  def resolve_layout
    case action_name
    when "show"
      "room"
    else
      "dashboard"
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #    super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
layout "dashboard"

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Account details updated successfully"
    else    
      render 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_dashboard_side_navigation.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to dashboard_path, class: "nav-link" do %>
              <i class="fas fa-home"></i>
              Dashboard
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to users_path, class: "nav-link" do %>
              <i class="fas fa-users"></i>
              Members
            <% end %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

app/views/dashboard/_dashboard_top_navigation.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
    <i class="fas fa-egg"></i> <span class="ml-2">work.</span>
  </a>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to("Sign out", destroy_user_session_path, class: "nav-link account", method: :delete) %>
        <i class="fas fa-user-circle"></i>
      </a>
    </li>
  </ul>
</nav>

app/views/dashboard/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<h1 class="h2">Dashboard</h1>
<div class="btn-toolbar mb-2 mb-md-0">
  <div class="btn-group mr-2">
    <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
    <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
  </div>
  <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
    <span data-feather="calendar"></span>
    This week
  </button>
</div>
</div>

<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

<script>
    var ctx = document.getElementById('myChart')
  // eslint-disable-next-line no-unused-vars
  var myChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: [
        'Sunday',
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday'
      ],
      datasets: [{
        data: [
          15339,
          21345,
          18483,
          24003,
          23489,
          24092,
          12034
        ],
        lineTension: 0,
        backgroundColor: 'transparent',
        borderColor: '#007bff',
        borderWidth: 4,
        pointBackgroundColor: '#007bff'
      }]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: false
          }
        }]
      },
      legend: {
        display: false
      }
    }
  });
</script>

<h2>Section title</h2>
<div class="table-responsive">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>#</th>
      <th>Header</th>
      <th>Header</th>
      <th>Header</th>
      <th>Header</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1,001</td>
      <td>Lorem</td>
      <td>ipsum</td>
      <td>dolor</td>
      <td>sit</td>
    </tr>
    <tr>
      <td>1,002</td>
      <td>amet</td>
      <td>consectetur</td>
      <td>adipiscing</td>
      <td>elit</td>
    </tr>
    <tr>
      <td>1,003</td>
      <td>Integer</td>
      <td>nec</td>
      <td>odio</td>
      <td>Praesent</td>
    </tr>
    <tr>
      <td>1,003</td>
      <td>libero</td>
      <td>Sed</td>
      <td>cursus</td>
      <td>ante</td>
    </tr>
    <tr>
      <td>1,004</td>
      <td>dapibus</td>
      <td>diam</td>
      <td>Sed</td>
      <td>nisi</td>
    </tr>
    <tr>
      <td>1,005</td>
      <td>Nulla</td>
      <td>quis</td>
      <td>sem</td>
      <td>at</td>
    </tr>
    <tr>
      <td>1,006</td>
      <td>nibh</td>
      <td>elementum</td>
      <td>imperdiet</td>
      <td>Duis</td>
    </tr>
    <tr>
      <td>1,007</td>
      <td>sagittis</td>
      <td>ipsum</td>
      <td>Praesent</td>
      <td>mauris</td>
    </tr>
    <tr>
      <td>1,008</td>
      <td>Fusce</td>
      <td>nec</td>
      <td>tellus</td>
      <td>sed</td>
    </tr>
    <tr>
      <td>1,009</td>
      <td>augue</td>
      <td>semper</td>
      <td>porta</td>
      <td>Mauris</td>
    </tr>
    <tr>
      <td>1,010</td>
      <td>massa</td>
      <td>Vestibulum</td>
      <td>lacinia</td>
      <td>arcu</td>
    </tr>
    <tr>
      <td>1,011</td>
      <td>eget</td>
      <td>nulla</td>
      <td>Class</td>
      <td>aptent</td>
    </tr>
    <tr>
      <td>1,012</td>
      <td>taciti</td>
      <td>sociosqu</td>
      <td>ad</td>
      <td>litora</td>
    </tr>
    <tr>
      <td>1,013</td>
      <td>torquent</td>
      <td>per</td>
      <td>conubia</td>
      <td>nostra</td>
    </tr>
    <tr>
      <td>1,014</td>
      <td>per</td>
      <td>inceptos</td>
      <td>himenaeos</td>
      <td>Curabitur</td>
    </tr>
    <tr>
      <td>1,015</td>
      <td>sodales</td>
      <td>ligula</td>
      <td>in</td>
      <td>libero</td>
    </tr>
  </tbody>
</table>
</div>

app/views/rooms/_room_daily_detail.html.erb
<div class="mb-5 pb-4">

    <div class="row booking-details mt-3">
        <div class="col-1 p-0 m-auto">
            <div class="no-booking-circle"></div>
        </div>
        <div class="col pl-0">
           <!--  7:35 - 8:30 -->

        </div>
        <div class="col text-right time-remaining">
            55 minutes
        </div>
    </div>
<% @bookings.each do |booking| %>
    <div class="row booking-details mt-3">
        <div class="col-1 p-0">
            <div class="booked-shape status-in-queue"></div>
        </div>
        <div class="col">
            <div class="row">
                <%= booking.start.strftime("%H:%M") %>
            </div>
            <div class="col-1">
            </div>
            <div class="col booking-content">
                <div class="row pb-2">
                    <div class="col-2 my-auto">
                        <i class="fas fa-user"></i>
                    </div> 
                    <div class="col pl-3">
                        <%= booking.user.full_name %>
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-2 my-auto">
                        <i class="fas fa-align-justify"></i>    
                    </div>
                    <div class="col pl-3">
                        <%= booking.description %>
                    </div>
                </div>
            </div>

            <div class="row">
                <%= booking.end.strftime("%H:%M") %>
            </div>
        </div>
        <div class="col-1 mr-5 mt-5 booking-content">
            <i class="fas fa-redo"></i>
        </div>
    </div>
<% end %>
<!-- 

    <div class="row booking-details mt-3">
        <div class="col-1 p-0 m-auto">
            <div class="no-booking-circle"></div>
        </div>
        <div class="col pl-0">
            9:30 - 10:30
        </div>
        <div class="col text-right time-remaining">
            1 hour
        </div>
    </div>

    <div class="row booking-details mt-3">
        <div class="col-1 p-0">
            <div class="booked-shape status-in-queue"></div>
        </div>
        <div class="col">
            <div class="row">
                10:30
            </div>
            <div class="col-1">
            </div>
            <div class="col booking-content">
                <div class="row pb-2">
                    <div class="col-2 my-auto">
                        <i class="fas fa-user"></i>
                    </div> 
                    <div class="col pl-3">
                        Jim Halpert
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-2 my-auto">
                        <i class="fas fa-align-justify"></i>    
                    </div>
                    <div class="col pl-3">
                        Interview
                    </div>
                </div>
            </div>
            <div class="row">
                11:30
            </div>
        </div>
        <div class="col-1 mr-5 mt-5 booking-content">
            
        </div>
    </div>

    <div class="row booking-details mt-3">
        <div class="col-1 p-0 m-auto">
            <div class="no-booking-circle"></div>
        </div>
        <div class="col pl-0">
            11:30 - 12:30
        </div>
        <div class="col text-right time-remaining">
            1 hour
        </div>
    </div>

    <div class="row booking-details mt-3">
        <div class="col-1 p-0">
            <div class="booked-shape status-in-queue"></div>
        </div>
        <div class="col">
            <div class="row">
                12:30
            </div>
            <div class="col-1">
            </div>
            <div class="col booking-content">
                <div class="row pb-2">
                    <div class="col-2 my-auto">
                        <i class="fas fa-user"></i>
                    </div> 
                    <div class="col pl-3">
                        Epic Coworking
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-2 my-auto">
                        <i class="fas fa-align-justify"></i>    
                    </div>
                    <div class="col pl-3">
                        Member's Lunch
                    </div>
                </div>
            </div>
            <div class="row">
                13:30
            </div>
        </div>
        <div class="col-1 mr-5 mt-5 booking-content">
            
        </div>
    </div>

        <div class="row booking-details mt-3">
        <div class="col-1 p-0 m-auto">
            <div class="no-booking-circle"></div>
        </div>
        <div class="col pl-0">
            13:00 - 16:00
        </div>
        <div class="col text-right time-remaining">
            3 hours
        </div>
    </div>

        <div class="row booking-details mt-3">
        <div class="col-1 p-0">
            <div class="booked-shape status-in-queue"></div>
        </div>
        <div class="col">
            <div class="row">
                16:00
            </div>
            <div class="col-1">
            </div>
            <div class="col booking-content">
                <div class="row pb-2">
                    <div class="col-2 my-auto">
                        <i class="fas fa-user"></i>
                    </div> 
                    <div class="col pl-3">
                        Epic Coworking
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-2 my-auto">
                        <i class="fas fa-align-justify"></i>    
                    </div>
                    <div class="col pl-3">
                        5 Steps to get more clients
                    </div>
                </div>
            </div>
            <div class="row">
                17:00
            </div>
        </div>
        <div class="col-1 mr-5 mt-5 booking-content">
            
        </div>
    </div>
 -->

</div>

app/views/rooms/index.html.erb
<div class="container">
<div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Resource Name</th>
          <th>Number</th>
          <th>Type</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
            <tr>
              <td><%= room.name %></td>
              <td><%= room.number %></td>
              <td><%= room.classification %></td>
              <td>
                <%= link_to "View", room_path(room.id), class: "badge badge-success" %>
                <%= link_to "Edit", edit_room_path(room.id), class: "badge badge-info" %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/rooms/show.html.erb
<div class="row m-0">
    <div class="col-5 resource-status status-avaliable fixed-top h-100">
        <div class="resource-status-header">
            <h2>Avaliable</h2>
            <h6>For the next 55 minutes</h6>
            <h1 class="text-center"><%= @time_now %></h1>
            <h6 class="text-center"><%= @date_now %></h6>
        </div>
        <div class="fixed-bottom px-4 my-5 pb-4">
            <div class="resorce-status-footer">
                <h2><%= @room.name %></h2>
                <h2><%= @room.number %></h2>
            </div>
        </div>
    </div>
    <nav class="navbar fixed-bottom navbar-light bg-light">
      <div class="nav-item">
        <h1><i class="fab fa-pied-piper-square"></i></h1>
      </div>
      <div class="nav-item">
        <ul class="list-inline m-0">
            <li class="list-inline-item mr-4">
                <a href="#" class="">
                    <h1><i class="fas fa-map-marker-alt"></i></h1>
                </a>
            </li>
            <li class="list-inline-item mr-3">
                <a href="#" class="">
                    <h1><i class="fas fa-bars"></i></h1>
                </a>
            </li>
        </ul>
      </div>
    </nav>
</div>

<div class="row">
    <div class="col-6 p-4">
        
    </div>
    <div class="col-6 p-4">
        <%= render 'rooms/room_daily_detail' %>
    </div> 
</div>

</div>

app/views/users/_feedback_detail.html.erb
<div class="card my-3">
    <div class="card-header">
        User Feedback
    </div>
    <div class="card-body">
        Body
    </div>
</div>

app/views/users/_member_activity.html.erb
<div class="card mt-3">
  <div class="card-header">
    <ul class="list-inline mb-0">
        <li class="list-inline-item">
            <i class="fas fa-angle-double-right"></i> Member Activity
        </li>
    </ul>
  </div>
  <div class="card-body">
    <div class="row">
        Some activity
    </div>
  </div>
</div>

app/views/users/_profile_detail.html.erb
<div class="card mt-3">
  <div class="card-header">
    <ul class="list-inline mb-0">
        <li class="list-inline-item">
            <i class="fas fa-address-card"></i> Profile Details
        </li>
        <li class="list-inline-item text-right">
            Edit profile
        </li>    
    </ul>

  </div>
  <div class="card-body">
    <div class="row">
        <div class="col">
            <div class="row">Name</div>
            <div class="row">Email</div>
            <div class="row">Phone</div>
        </div>
        <div class="col">
            <div class="row"><%= @user.full_name %></div>
            <div class="row"><%= @user.email %></div>
            <div class="row">+1 920 545 9774</div>
        </div>
  </div>
  </div>
</div>

app/views/users/_profile_header.html.erb
<div class="card">
    <div class="row">
        <div class="col-4">
            <img class="rounded-circle profile-image" alt="100x100" src="https://mdbootstrap.com/img/Photos/Avatars/img%20(21).jpg"data-holder-rendered="true">
        </div>
        <div class="col-5 mt-5">
            <div class="row">
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <h4><%= @user.full_name %></h4>
                </li>
                <li class="list-inline-item">
                    <span class="badge badge-pill badge-info">Admin</span>
                </li>    
            </ul>
            </div>
            <div class="row mb-3">
                <span class="text-muted">Field Artillery Officer</span>
            </div>
            <div class="row">
                <span class="badge badge-pill badge-success">Active</span>    
            </div>
        </div>
        <div class="col mt-5">
            <div class="row">
                <h4>Company</h4>
            </div>
            <div class="row">
                <span class="text-muted">United States Army</span>
            </div>
        </div>
    </div>
    <div class="row text-center">
        <div class="col border-right">
            Days Active:
            <h1>32</h1>
        </div>
        <div class="col border-right">
            Days a Member:
            <h1>108</h1>
        </div>
        <div class="col">
            Resources Booked:
            <h1>3</h1>
        </div>
    </div>
</div>

app/views/users/_subscription_detail.html.erb
    <div class="card">
      <div class="card-header">
        <ul class="list-inline mb-0">
            <li class="list-inline-item">
                <i class="fas fa-angle-double-right"></i> Subscription
            </li>
        </ul>
      </div>
      <div class="card-body">
        <div class="row border-bottom pb-3">
            <div class="col">
              Member Since
              12/3/2018
            </div>
            <div class="col">
              Subscription Ends
              2/3/2020
            </div>
        </div>
        <div class="row border-bottom py-3">
          <div class="col">
            Additional Features
            None
          </div>
          <div class="col">
            Subscription Type
            Premium
          </div>
        </div>
        <div class="row pt-3">
          <div class="d-block w-100 mx-1">
          <div class="progress">
            <div class="progress-bar progress-bar-striped progress-bar-animated bg-success" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%">XX days until next payment</div>
          </div>
        </div>
        </div>
      </div>
    </div>

app/views/users/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h1 class="h2">Member Index</h1>
</div>

<div class="table-responsive">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Permissions</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.full_name %></td>
          <td><%= user.email %></td>
          <td>Permissions</td>
          <td>
            <%= link_to "View", user_path(user.id), class: "badge badge-success" %>
            <%= link_to "Edit", edit_user_path(user.id), class: "badge badge-info" %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h1 class="h2">
        View Profile
    </h1>
</div>

<div class="row">
    <div class="col-8 px-1">
        <%= render 'users/profile_header' %>
        <%= render 'users/profile_detail' %>
        <%= render 'users/member_activity' %>
    </div>
    <div class="col px-1">
        <%= render 'users/subscription_detail' %>
        <%= render 'users/feedback_detail' %>
    </div>
</div>